export const NEW_TAG_REQUEST = 'NEW_TAG_REQUEST';
export const NEW_URL_REQUEST = 'NEW_URL_REQUEST';
export const RECEIVE_TAG_RESPONSE = 'RECEIVE_TAG_RESPONSE';
export const RECEIVE_URL_RESPONSE = 'RECEIVE_URL_RESPONSE';
export const RECEIVE_ERROR = 'RECEIVE_ERROR';
export const RESET_STATE = 'RESET_STATE';